import pygame


#SCREEN_WIDTH = 1280
#SCREEN_HEIGHT = 720
pygame.display.init()
display = pygame.display.get_desktop_sizes()
SCREEN_WIDTH = display[0][0] - 15
SCREEN_HEIGHT = display[0][1] - 10


PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
ASTEROID_MIN_RADIUS = 40
ASTEROID_KINDS = 4
ASTEROID_SPAWN_RATE_SECONDS = 0.5
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * 1.4 ** ASTEROID_KINDS
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.2
ROCKET_SOUND_COOLDOWN_SECONDS = 1
FRICTION = 0.7